from . import avatar  # noqa: F401
from . import cart  # noqa: F401
from . import favorites  # noqa: F401
from . import ingredients  # noqa: F401
from . import link  # noqa: F401
from . import login  # noqa: F401
from . import recipes  # noqa: F401
from . import register  # noqa: F401
from . import subscription  # noqa: F401
from . import tags  # noqa: F401
from . import user_reciepe_relation  # noqa: F401
from . import users  # noqa: F401
