# Number of objects on page
PAGINATE_COUNT = 10

# Maximum number of objects on page
MAX_PAGE_SIZE = 100

# Maximum length of model fields
MAX_INGREDIENT_NAME_LENGTH = 100
MAX_MEASUREMENT_UNIT_LENGTH = 100
MAX_RECIPE_TITLE_LENGTH = 100
MAX_TAG_NAME_LENGTH = 100
MAX_TAG_SLUG_LENGTH = 100
MAX_USERNAME_LENGTH = 150
MAX_EMAIL_LENGTH = 254
MAX_FIRST_NAME_LENGTH = 150
MAX_LAST_NAME_LENGTH = 150
MAX_PASSWORD_LENGTH = 254
