# Generated by Django 5.2.5 on 2025-09-07 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_alter_ingredient_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.SmallIntegerField(help_text='Время приготовления в минутах', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
