# Generated by Django 5.2.5 on 2025-09-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_cart_unique_cart_relation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='name',
        ),
    ]
