# Generated by Django 5.2.5 on 2025-09-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_rename_title_recipe_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
