# Generated by Django 5.2.6 on 2025-09-10 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0022_alter_cart_recipe_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
