# Generated by Django 5.2.5 on 2025-09-01 13:06

import apiuser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apiuser.models.user_avatar_path),
        ),
    ]
